# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wasserstein_distance <- function(Diag1, Diag2, q, internal_p, delta = 0.01, initial_eps = 1, eps_factor = 5.0) {
    .Call('_kernelTDA_wasserstein_distance', PACKAGE = 'kernelTDA', Diag1, Diag2, q, internal_p, delta, initial_eps, eps_factor)
}

